# Файл настроек должен содержать обязательные объекты:
#   settings - Базовые настройки прокси
#   db - Настройки подключения к SQL-серверу приложения
#   Aeroclub - Агентство
#   CbtcTravelclick - Агентство
#   logging_config - настройки для логирования (консоль, файл, почта)

settings:
  nestleProxy: http://pac.zscaler.net/nestle.com/EUR_proxy.pac
  proxyIp: 204.79.90.44:8080
  debug_limit_off: True

smtp:
  mailuser: dummy_mailuser
  password: gAAAAABnERFzl8C7ZTzdSF0Mhq84YLOsiADHYApRMX_U3SaK5DZNH6MlUEUfnkmY_eOcdfVa_jdvcDZwu-ehPm2vTj84yt4b7g==

db:
  driver: SQL Server
  server: rumosd1679\psapp01, 40011
  database: SAPHR

AeroClub:
  devUrl: https://beta-integration.aeroclub.ru/hub/profiles/synchronization
  devSourceUrl: beta-integration.aeroclub.ru
  url: https://integration.aeroclub.ru/hub/profiles/synchronization
  sourceUrl: integration.aeroclub.ru
  username: dummy_user
  password: gAAAAABnERFzl8C7ZTzdSF0Mhq84YLOsiADHYApRMX_U3SaK5DZNH6MlUEUfnkmY_eOcdfVa_jdvcDZwu-ehPm2vTj84yt4b7g==
  userAgent: Nestle Integratoin <Aleksandr.Vinnikov@ru.nestle.com>

  companies:
    RU12:
      id: CEREAL_PARTNERS_RUS
      minCounter: 1
      storedProc: dbo.GetAeroClubData_RU12
    
    RU19:
      id: NESTLE_KUBAN
      minCounter: 1
      storedProc: dbo.GetAeroClubData_RU19

    RU37:
      id: NESTLE_RUSSIA
      minCounter: 1
      storedProc: dbo.GetAeroClubData_RU37
    
    RU44:
      id: ATRIUM_INNOVATIONS
      minCounter: 1
      storedProc: dbo.GetAeroClubData_RU44

    RU45:
      id: NSBS_SAMARA
      minCounter: 1
      storedProc: dbo.GetAeroClubData_RU45

CbtcTravelClick:
  url: https://dev.travel-click.ru/rest/api/employees/upload/json
  username: dummy_user
  password: gAAAAABnERFzl8C7ZTzdSF0Mhq84YLOsiADHYApRMX_U3SaK5DZNH6MlUEUfnkmY_eOcdfVa_jdvcDZwu-ehPm2vTj84yt4b7g==
  minCounter: 1
  storedProc: dbo.GetCBTCData

  travel_dev:
    url: https://dev.travel-click.ru/rest/api/employees/upload/json
    password: gAAAAABnERGU7P4u6axkh-J8diGCCoRN2RkTiwxnXEIHrZTMapXoHp8yuKLIO6YSQtl01IjdWnZzOaRn3M2GKNBJxUBYv237-Q==

  newUser:
    password: gAAAAABnERGU7P4u6axkh-J8diGCCoRN2RkTiwxnXEIHrZTMapXoHp8yuKLIO6YSQtl01IjdWnZzOaRn3M2GKNBJxUBYv237-Q==
    holdingUserRole: sbt_manager
    holdingUserPolicy: HOLDING
    otherUserPolicy: SELF

  companies:
    CBTCRU12:
      id: Сириал Партнерс Рус ООО Пермь
      confirm: "TRUE"
      fullUpdate: "FALSE"
      incrementUpdate: "TRUE"

    CBTCRU37:
      id: Нестле Россия ООО
      confirm: "TRUE"
      fullUpdate: "FALSE"
      incrementUpdate: "TRUE"

logging_config:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      formatter: brief
      level: INFO
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: common
      level: DEBUG
      filename: .\logs\AeroTravelLog
      maxBytes: 1000000
      backupCount: 10
    mail:
      class: logging.handlers.SMTPHandler
      level: WARNING
      formatter: common
      mailhost: ['smtp.nestlesoft.net', 587]
      credentials: ['DoNotUseUserNameHere', 'SetEncriptedPassInSMTPSection']
      secure: []
      fromaddr: RUITBSI@internal.nestle.com
      toaddrs:
        - Vsevolod.Russov@ru.nestle.com
        - Vsevolod.Russov@ru.nestle.com
      subject: problem with AeroTravel
  formatters:
    brief:
      format: '%(levelname)s: [%(name)s] > %(message)s'
    common:
      format: '%(levelname)s: %(asctime)s - [%(name)s] %(funcName)s:(%(lineno)d) > %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  root:
    level: DEBUG
    handlers: [file, console, mail]


